/*
 * Internal module API header file.
 *
 * Generated by SIP 4.15.5 on Sat Mar 12 13:28:43 2016
 */

#ifndef _wordAPI_H
#define _wordAPI_H


#include <sip.h>

/*
 * Convenient names to refer to various strings defined in this module.
 * Only the class names are part of the public API.
 */
#define sipNameNr_reverse 0
#define sipName_reverse &sipStrings_word[0]
#define sipNameNr_Word 8
#define sipName_Word &sipStrings_word[8]
#define sipNameNr_word 13
#define sipName_word &sipStrings_word[13]

#define sipMalloc                   sipAPI_word->api_malloc
#define sipFree                     sipAPI_word->api_free
#define sipBuildResult              sipAPI_word->api_build_result
#define sipCallMethod               sipAPI_word->api_call_method
#define sipCallErrorHandler         sipAPI_word->api_call_error_handler
#define sipParseResultEx            sipAPI_word->api_parse_result_ex
#define sipParseResult              sipAPI_word->api_parse_result
#define sipParseArgs                sipAPI_word->api_parse_args
#define sipParseKwdArgs             sipAPI_word->api_parse_kwd_args
#define sipParsePair                sipAPI_word->api_parse_pair
#define sipCommonDtor               sipAPI_word->api_common_dtor
#define sipConvertFromSequenceIndex sipAPI_word->api_convert_from_sequence_index
#define sipConvertFromVoidPtr       sipAPI_word->api_convert_from_void_ptr
#define sipConvertToVoidPtr         sipAPI_word->api_convert_to_void_ptr
#define sipAddException             sipAPI_word->api_add_exception
#define sipNoFunction               sipAPI_word->api_no_function
#define sipNoMethod                 sipAPI_word->api_no_method
#define sipAbstractMethod           sipAPI_word->api_abstract_method
#define sipBadClass                 sipAPI_word->api_bad_class
#define sipBadCatcherResult         sipAPI_word->api_bad_catcher_result
#define sipBadCallableArg           sipAPI_word->api_bad_callable_arg
#define sipBadOperatorArg           sipAPI_word->api_bad_operator_arg
#define sipTrace                    sipAPI_word->api_trace
#define sipTransferBack             sipAPI_word->api_transfer_back
#define sipTransferTo               sipAPI_word->api_transfer_to
#define sipTransferBreak            sipAPI_word->api_transfer_break
#define sipSimpleWrapper_Type       sipAPI_word->api_simplewrapper_type
#define sipWrapper_Type             sipAPI_word->api_wrapper_type
#define sipWrapperType_Type         sipAPI_word->api_wrappertype_type
#define sipVoidPtr_Type             sipAPI_word->api_voidptr_type
#define sipGetPyObject              sipAPI_word->api_get_pyobject
#define sipGetAddress               sipAPI_word->api_get_address
#define sipGetMixinAddress          sipAPI_word->api_get_mixin_address
#define sipGetCppPtr                sipAPI_word->api_get_cpp_ptr
#define sipGetComplexCppPtr         sipAPI_word->api_get_complex_cpp_ptr
#define sipIsPyMethod               sipAPI_word->api_is_py_method
#define sipCallHook                 sipAPI_word->api_call_hook
#define sipEndThread                sipAPI_word->api_end_thread
#define sipConnectRx                sipAPI_word->api_connect_rx
#define sipDisconnectRx             sipAPI_word->api_disconnect_rx
#define sipRaiseUnknownException    sipAPI_word->api_raise_unknown_exception
#define sipRaiseTypeException       sipAPI_word->api_raise_type_exception
#define sipBadLengthForSlice        sipAPI_word->api_bad_length_for_slice
#define sipAddTypeInstance          sipAPI_word->api_add_type_instance
#define sipFreeSipslot              sipAPI_word->api_free_sipslot
#define sipSameSlot                 sipAPI_word->api_same_slot
#define sipPySlotExtend             sipAPI_word->api_pyslot_extend
#define sipConvertRx                sipAPI_word->api_convert_rx
#define sipAddDelayedDtor           sipAPI_word->api_add_delayed_dtor
#define sipCanConvertToType         sipAPI_word->api_can_convert_to_type
#define sipConvertToType            sipAPI_word->api_convert_to_type
#define sipForceConvertToType       sipAPI_word->api_force_convert_to_type
#define sipCanConvertToEnum         sipAPI_word->api_can_convert_to_enum
#define sipReleaseType              sipAPI_word->api_release_type
#define sipConvertFromType          sipAPI_word->api_convert_from_type
#define sipConvertFromNewType       sipAPI_word->api_convert_from_new_type
#define sipConvertFromNewPyType     sipAPI_word->api_convert_from_new_pytype
#define sipConvertFromEnum          sipAPI_word->api_convert_from_enum
#define sipGetState                 sipAPI_word->api_get_state
#define sipLong_AsUnsignedLong      sipAPI_word->api_long_as_unsigned_long
#define sipExportSymbol             sipAPI_word->api_export_symbol
#define sipImportSymbol             sipAPI_word->api_import_symbol
#define sipFindType                 sipAPI_word->api_find_type
#define sipFindNamedEnum            sipAPI_word->api_find_named_enum
#define sipBytes_AsChar             sipAPI_word->api_bytes_as_char
#define sipBytes_AsString           sipAPI_word->api_bytes_as_string
#define sipString_AsASCIIChar       sipAPI_word->api_string_as_ascii_char
#define sipString_AsASCIIString     sipAPI_word->api_string_as_ascii_string
#define sipString_AsLatin1Char      sipAPI_word->api_string_as_latin1_char
#define sipString_AsLatin1String    sipAPI_word->api_string_as_latin1_string
#define sipString_AsUTF8Char        sipAPI_word->api_string_as_utf8_char
#define sipString_AsUTF8String      sipAPI_word->api_string_as_utf8_string
#define sipUnicode_AsWChar          sipAPI_word->api_unicode_as_wchar
#define sipUnicode_AsWString        sipAPI_word->api_unicode_as_wstring
#define sipConvertFromConstVoidPtr  sipAPI_word->api_convert_from_const_void_ptr
#define sipConvertFromVoidPtrAndSize    sipAPI_word->api_convert_from_void_ptr_and_size
#define sipConvertFromConstVoidPtrAndSize   sipAPI_word->api_convert_from_const_void_ptr_and_size
#define sipInvokeSlot               sipAPI_word->api_invoke_slot
#define sipSaveSlot                 sipAPI_word->api_save_slot
#define sipClearAnySlotReference    sipAPI_word->api_clear_any_slot_reference
#define sipVisitSlot                sipAPI_word->api_visit_slot
#define sipWrappedTypeName(wt)      ((wt)->type->td_cname)
#define sipDeprecated               sipAPI_word->api_deprecated
#define sipKeepReference            sipAPI_word->api_keep_reference
#define sipRegisterProxyResolver    sipAPI_word->api_register_proxy_resolver
#define sipRegisterPyType           sipAPI_word->api_register_py_type
#define sipTypeFromPyTypeObject     sipAPI_word->api_type_from_py_type_object
#define sipTypeScope                sipAPI_word->api_type_scope
#define sipResolveTypedef           sipAPI_word->api_resolve_typedef
#define sipRegisterAttributeGetter  sipAPI_word->api_register_attribute_getter
#define sipIsAPIEnabled             sipAPI_word->api_is_api_enabled
#define sipSetDestroyOnExit         sipAPI_word->api_set_destroy_on_exit
#define sipEnableAutoconversion     sipAPI_word->api_enable_autoconversion
#define sipInitMixin                sipAPI_word->api_init_mixin
#define sipExportModule             sipAPI_word->api_export_module
#define sipInitModule               sipAPI_word->api_init_module

/* These are deprecated. */
#define sipMapStringToClass         sipAPI_word->api_map_string_to_class
#define sipMapIntToClass            sipAPI_word->api_map_int_to_class
#define sipFindClass                sipAPI_word->api_find_class
#define sipFindMappedType           sipAPI_word->api_find_mapped_type
#define sipConvertToArray           sipAPI_word->api_convert_to_array
#define sipConvertToTypedArray      sipAPI_word->api_convert_to_typed_array
#define sipWrapper_Check(w)         PyObject_TypeCheck((w), sipAPI_word->api_wrapper_type)
#define sipGetWrapper(p, wt)        sipGetPyObject((p), (wt)->type)
#define sipReleaseInstance(p, wt, s)    sipReleaseType((p), (wt)->type, (s))
#define sipReleaseMappedType        sipReleaseType
#define sipCanConvertToInstance(o, wt, f)   sipCanConvertToType((o), (wt)->type, (f))
#define sipCanConvertToMappedType   sipCanConvertToType
#define sipConvertToInstance(o, wt, t, f, s, e)     sipConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipConvertToMappedType      sipConvertToType
#define sipForceConvertToInstance(o, wt, t, f, s, e)    sipForceConvertToType((o), (wt)->type, (t), (f), (s), (e))
#define sipForceConvertToMappedType sipForceConvertToType
#define sipConvertFromInstance(p, wt, t)    sipConvertFromType((p), (wt)->type, (t))
#define sipConvertFromMappedType    sipConvertFromType
#define sipConvertFromNamedEnum(v, pt)  sipConvertFromEnum((v), ((sipEnumTypeObject *)(pt))->type)
#define sipConvertFromNewInstance(p, wt, t) sipConvertFromNewType((p), (wt)->type, (t))

/* The strings used by this module. */
extern const char sipStrings_word[];

#define sipType_Word              sipModuleAPI_word.em_types[0]
#define sipClass_Word             sipModuleAPI_word.em_types[0]->u.td_wrapper_type

extern sipClassTypeDef sipTypeDef_word_Word;

/* The SIP API, this module's API and the APIs of any imported modules. */
extern const sipAPIDef *sipAPI_word;
extern sipExportedModuleDef sipModuleAPI_word;

#endif
